services:
  - type: web
    name: bigmarble-ai-training-portal
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    # Supabase environment variables - you'll need to add these in Render dashboard
    # - key: NEXT_PUBLIC_SUPABASE_URL
    #   value: your-supabase-project-url
    # - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    #   value: your-supabase-anon-key
    # - key: SUPABASE_SERVICE_ROLE_KEY
    #   value: your-supabase-service-role-key